[package]
name = "json_scientist"
version = "0.1.0"
authors = ["James Mountain <31282623+jmountain-hmrc@users.noreply.github.com>"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"